# Generated by Django 3.0.3 on 2020-06-29 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='departmen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Departmens'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=13),
        ),
    ]
