# Generated by Django 3.0.3 on 2020-07-01 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_users_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='departmen',
            new_name='department',
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=13, unique=True),
        ),
    ]
